### ISSUE TITLE
Bug with setting diagonal elements to zero (corner case)

### ISSUE THREAD

**Issue by ODemidenko** [franckjay/TorchEASE#8]
I don't understand how this code could set diagonal elements to zero. It looks like a bug to me, or am I missing smth?

```python
B = B + torch.eye(B.shape[0]) #Set diagonals to 0
```
I guess, it must be
```python
B = B * (1 - torch.eye(B.shape[0]))
```

This doesn't affect predicting new items to recommend, but leads to overestimation of known user preferences. Their correct estimation is relevent in case we want to tune regularization and checkout that as top recommendations it predicts the known items

**Comment by franckjay** [comment]
Hi @ODemidenko , thank you for reaching out. To me it seems like the diagonals get set to zero, but maybe I am missing something as well. Here is a test case:
```
G = torch.randn(4, 4)
'''
tensor([[-0.1985, -0.8391,  0.9857,  0.6301],
        [ 0.7443,  0.8555, -1.3910,  0.6625],
        [ 0.4113,  0.0571, -0.4015,  2.4421],
        [ 0.5748, -0.8791,  0.9026,  1.3297]])
'''
P = G.inverse()
B = P / (-1 * P.diag())
'''
 tensor([[ -1.0000,  -0.0470,   0.1351, -18.9357],
        [ -5.1499,  -1.0000,  -1.4709, -31.4554],
        [ -3.8675,  -0.7970,  -1.0000, -29.9533],
        [ -0.3471,  -0.0997,  -0.3520,  -1.0000]])
'''
B = B + torch.eye(B.shape[0])
'''
tensor([[  0.0000,  -0.0470,   0.1351, -18.9357],
        [ -5.1499,   0.0000,  -1.4709, -31.4554],
        [ -3.8675,  -0.7970,   0.0000, -29.9533],
        [ -0.3471,  -0.0997,  -0.3520,   0.0000]])
'''
```

Feel free to reopen if I am missing something!
